context("K-Partitions")

test_that("Integer partitions in k parts - npartitions", {
    expect_equal(npartitions(20, 10), 42)
    expect_equal(npartitions(20, 21), 0)
    expect_equal(sum(sapply(1:20, function(k) npartitions(20, k))), 627)
    expect_equal(npartitions(100, 10), 2977866)
    expect_error(npartitions(200, 50), "integer overflow")
    expect_equal(npartitions(20, 10, bigz = TRUE), 42)
    expect_equal(npartitions(100, 10, bigz = TRUE), 2977866)
    expect_equal(npartitions(200, 50, bigz = TRUE), gmp::as.bigz("39403290219"))
    expect_error(npartitions(20, 0), "positive integer")
})

test_that("Integer k-partitions - ascending partitions", {
    part <- partitions(20, 10)
    expect_equal(nrow(part), 42)
    expect_equal(ncol(part), 10)
    expect_equal(part[1, ], c(rep(1, 9), 11))
    expect_equal(part[2, ], c(rep(1, 8), 2, 10))
    expect_equal(part[42, ], rep(2, 10))
    expect_true(all(apply(part, 1, sum) == 20))

    part <- partitions(20, 10, type = "c")
    expect_equal(nrow(part), 10)
    expect_equal(ncol(part), 42)
    expect_equal(part[, 1], c(rep(1, 9), 11))
    expect_equal(part[, 2], c(rep(1, 8), 2, 10))
    expect_equal(part[, 42], rep(2, 10))
    expect_true(all(apply(part, 2, sum) == 20))

    part <- partitions(20, 10, type = "l")
    expect_length(part, 42)
    expect_equal(part[[1]], c(rep(1, 9), 11))
    expect_equal(part[[2]], c(rep(1, 8), 2, 10))
    expect_equal(part[[42]], rep(2, 10))
    expect_true(all(sapply(part, sum) == 20))

    expect_error(partitions(200, 50), "too many results")
})

test_that("Integer k-partitions - descending partitions", {
    part <- partitions(20, 10, descending = TRUE)
    expect_equal(nrow(part), 42)
    expect_equal(ncol(part), 10)
    expect_equal(part[1, ], c(11, rep(1, 9)))
    expect_equal(part[2, ], c(10, 2, rep(1, 8)))
    expect_equal(part[42, ], rep(2, 10))
    expect_true(all(apply(part, 1, sum) == 20))

    part <- partitions(20, 10, descending = TRUE, type = "c")
    expect_equal(nrow(part), 10)
    expect_equal(ncol(part), 42)
    expect_equal(part[, 1], c(11, rep(1, 9)))
    expect_equal(part[, 2], c(10, 2, rep(1, 8)))
    expect_equal(part[, 42], rep(2, 10))
    expect_true(all(apply(part, 2, sum) == 20))

    part <- partitions(20, 10, descending = TRUE, type = "l")
    expect_length(part, 42)
    expect_equal(part[[1]], c(11, rep(1, 9)))
    expect_equal(part[[2]], c(10, 2, rep(1, 8)))
    expect_equal(part[[42]], rep(2, 10))
    expect_true(all(sapply(part, sum) == 20))

    expect_error(partitions(200, 50), "too many results")
})

test_that("Integer k-partitions - ascending ipartitions", {
    part <- partitions(20, 10)
    ipart <- ipartitions(20, 10)
    expect_is(ipart, "Partitions")
    expect_equal(ipart$collect(), part)
    expect_equal(ipart$getnext(), part[1, ])
    expect_equal(ipart$getnext(), part[2, ])
    expect_equal(ipart$getnext(2), part[3:4, ])

    part <- partitions(20, 10, type = "c")
    ipart$reset()
    expect_equal(ipart$collect(type = "c"), part)
    expect_equal(ipart$getnext(type = "c"), part[, 1])
    expect_equal(ipart$getnext(type = "c"), part[, 2])
    expect_equal(ipart$getnext(2, type = "c"), part[, 3:4])

    part <- partitions(20, 10, type = "l")
    ipart$reset()
    expect_equal(ipart$collect(type = "l"), part)
    expect_equal(ipart$getnext(type = "l"), part[[1]])
    expect_equal(ipart$getnext(type = "l"), part[[2]])
    expect_equal(ipart$getnext(2, type = "l"), part[3:4])
})

test_that("Integer partitions - descending ipartitions", {
    part <- partitions(20, 10, descending = TRUE)
    ipart <- ipartitions(20, 10, descending = TRUE)
    expect_is(ipart, "Partitions")
    expect_equal(ipart$collect(), part)
    expect_equal(ipart$getnext(), part[1, ])
    expect_equal(ipart$getnext(), part[2, ])
    expect_equal(ipart$getnext(2), part[3:4, ])

    part <- partitions(20, 10, descending = TRUE, type = "c")
    ipart$reset()
    expect_equal(ipart$collect(type = "c"), part)
    expect_equal(ipart$getnext(type = "c"), part[, 1])
    expect_equal(ipart$getnext(type = "c"), part[, 2])
    expect_equal(ipart$getnext(2, type = "c"), part[, 3:4])

    part <- partitions(20, 10, descending = TRUE, type = "l")
    ipart$reset()
    expect_equal(ipart$collect(type = "l"), part)
    expect_equal(ipart$getnext(type = "l"), part[[1]])
    expect_equal(ipart$getnext(type = "l"), part[[2]])
    expect_equal(ipart$getnext(2, type = "l"), part[3:4])
})
